### ISSUE TITLE
Format lib/src/http

### ISSUE THREAD

**Issue by milos94** [damjanstanisavljevic/minichat#1]
In the lib/src/http format all of the files to have consistent coding style and add comments for doxygen

- [x] body.hpp
- [x] headers.hpp
- [x] method.hpp
- [x] request.hpp
- [x] uri.hpp
- [x] version.hpp

Create a page with coding guidelines.

Sprints: 1,2

Branch: https://github.com/damjanstanisavljevic/minichat/tree/issue_1

**Comment by damjanstanisavljevic** [comment]
Not finished in Sprint 1, because @milos94 didn't have time.
