### ISSUE TITLE
boost::asio test

### ISSUE THREAD

**Issue by milos94** [damjanstanisavljevic/minichat#2]
Create a test application using boost::asio that simply sends/receives requests (lib/src/http).
Create a short presentation on how the app works and some details on boost::asio.

Development made for this issue is saved on a separate branch or just attached as a file so that it can be used as base if needed in the future. This issue will NOT be merged to the trunk.

Sprints: 1,2

**Comment by damjanstanisavljevic** [comment]
Not finished in Sprint 1, turned out to be more complicated than expected.
